"""cascade document questions

Revision ID: 04a8ca9baff7
Revises: 8d0e85c9d921
Create Date: 2026-08-08 12:25:03.243881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04a8ca9baff7'
down_revision: Union[str, Sequence[str], None] = '8d0e85c9d921'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('document_questions_document_id_fkey'), 'document_questions', type_='foreignkey')
    op.create_foreign_key(None, 'document_questions', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'document_questions', type_='foreignkey')
    op.create_foreign_key(op.f('document_questions_document_id_fkey'), 'document_questions', 'documents', ['document_id'], ['id'])
    # ### end Alembic commands ###
