"""add extracted text to documents

Revision ID: 110b5e1a79a7
Revises: e0d2b4c649c0
Create Date: 2026-08-07 22:54:52.503425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '110b5e1a79a7'
down_revision: Union[str, Sequence[str], None] = 'e0d2b4c649c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    "documents",
    sa.Column(
        "status",
        sa.String(length=20),
        nullable=False,
        server_default="completed"
    )
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'extracted_text')
    # ### end Alembic commands ###
