"""add document status

Revision ID: 70c19b4451d8
Revises: d82f3b60eef5
Create Date: 2026-08-07 23:28:11.619164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70c19b4451d8'
down_revision: Union[str, Sequence[str], None] = 'd82f3b60eef5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    "documents",
    sa.Column(
        "status",
        sa.String(length=20),
        nullable=False,
        server_default="completed"
    )
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'status')
    # ### end Alembic commands ###
