"""add sources to document questions

Revision ID: 9b3684aa3acb
Revises: 753f20fc4810
Create Date: 2026-08-14 21:28:58.692957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9b3684aa3acb'
down_revision: Union[str, Sequence[str], None] = '753f20fc4810'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_questions', sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_questions', 'sources')
    # ### end Alembic commands ###
