"""add document summary

Revision ID: d82f3b60eef5
Revises: 110b5e1a79a7
Create Date: 2026-08-07 23:07:43.819444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd82f3b60eef5'
down_revision: Union[str, Sequence[str], None] = '110b5e1a79a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    "documents",
    sa.Column(
        "status",
        sa.String(length=20),
        nullable=False,
        server_default="completed"
    )
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'summary')
    # ### end Alembic commands ###
