"""add document file metadata

Revision ID: e0d2b4c649c0
Revises: 0dabcf8b521e
Create Date: 2026-08-07 22:38:58.349830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0d2b4c649c0'
down_revision: Union[str, Sequence[str], None] = '0dabcf8b521e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('stored_name', sa.String(length=255), nullable=False))
    op.add_column('documents', sa.Column('size_bytes', sa.BigInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'size_bytes')
    op.drop_column('documents', 'stored_name')
    # ### end Alembic commands ###
