"""add document insights

Revision ID: e91ca10277d9
Revises: 04a8ca9baff7
Create Date: 2026-08-08 13:43:09.218591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e91ca10277d9'
down_revision: Union[str, Sequence[str], None] = '04a8ca9baff7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('insights', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'insights')
    # ### end Alembic commands ###
