"""add favorite to documents

Revision ID: eb4b5103d76a
Revises: e91ca10277d9
Create Date: 2026-08-08 14:45:03.894334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb4b5103d76a'
down_revision: Union[str, Sequence[str], None] = 'e91ca10277d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    "documents",
    sa.Column(
        "is_favorite",
        sa.Boolean(),
        nullable=False,
        server_default=sa.false()
    )
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'is_favorite')
    # ### end Alembic commands ###
